### PR TITLE
Installation service refactor

### LINKED ISSUE #87: Broken Old Version Checking
image

The installation autoremove feature will not remove either one of these installation, even though one has to be older than the other.

### LINKED ISSUE #208: Refactor InstallationService and Installation (model)
InstallationService and Installation need to be refactored, right now these are a bit of a mess. For reference, the issues with #206 

What I am thinking for this:
- Change InstallationService to be polling based, rather than it pushing changes to the UI for further separation here.
- Move all of the file management from Installation to InstallationService
- Keep track of the installs and store this in a json file, rather than relying on the folder names in the install directory
  - Fork name
  - version
  - install path
  - last played date
- In the InstallationService startup we can get the list of servers from the ServerService, if no servers are using that fork and version, and the last played date was more than a week ago I think it would be safe to delete that installation. This should fix #87
- Same as above but add a button to manually do it
- When changing the installation directory the launcher should prompt them if they would like to move their current installs to the new directory
  - If they do not move them the installs from the old directory should still be available to launch, and get cleaned up still by the old version checker
  - If they choose to move them just move the folders for the current installs and update the where they are stored

These changes would limit the players ability to manually place fork installs into the installation directory, but I would consider that the be a security feature rather than missing functionality. If we need this in the future for whatever reason we can add a UI option somewhere to import an installation.

### LINKED ISSUE #209: Don't bundle unneeded Avalonia package in the release build
Thanks to PJB from SS14 for the heads up.

We are shipping the entire C# compiler as a dependency in our release build.

The fix is simple, we just make the following change in our csproj

https://github.com/space-wizards/SS14.Launcher/blob/17590d63c68b0f2b9e7bbf075a4492f9955c48c9/SS14.Launcher/SS14.Launcher.csproj#L36

### PR DESCRIPTION
**Pull request by CorruptComputer**
Changes:
- Refactors Download, Install, DownloadService, and InstallationService
  - The services have been combined into a single service, and the models only hold the data now.
- Refactors servers panel a bit
  - The servers panel made heavy use of both those services so it had to have pretty extensive changes done to accommodate the new code
- Refactored the message box from the auto-remove prompt out into a reusable component
- Fixes #208
  - No button to manually run the cleanup, but I decided that its not really needed since you can just toggle the checkbox on and off if you want it.
- Fixes #209
- Fixes #87
- Fixes most of #191 with the exception of ProgressStream 

Screenshots:
image
image
image

### CODE REVIEW

File: UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs [hunk 1]
```diff
@@ -92,10 +87,61 @@ private async Task OnAutoRemoveChangedAsync()
...
+
+            Log.Information("Scheduling periodic refresh for installations list...");
+            RxApp.MainThreadScheduler.SchedulePeriodic(_refreshInterval, RefreshInstallationsList);
+        }
+
+        private void RefreshInstallationsList()
+        {
+            List<Installation> installations = _installationService.GetInstallations();
+
+            // Add new
```
Comment (corp-0) [inline UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs]: comments like this and the one on line 119 look like they could be extracted into their own methods and use the name of the method as self-documentation.

File: UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs [hunk 2]
```diff
@@ -92,10 +87,61 @@ private async Task OnAutoRemoveChangedAsync()
...
+            // Remove old
+            for (int i = 0; i < InstallationViews.Count; i++)
+            {
+                InstallationViewModel viewModel = InstallationViews[i];
+                Installation? installation = installations.FirstOrDefault(inst => inst.InstallationId == viewModel.Installation.InstallationId);
+
+                if (installation == null)
+                {
+                    InstallationViews.Remove(viewModel);
+                    i--;
```
Comment (corp-0) [inline UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs]: wait, what is this doing?

Comment (corp-0) [reply UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs]: ah I see. Iterate from last to first instead

Comment (CorruptComputer) [reply UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs]: This is just bumping the iterator back one when it removes the element its currently on so that whatever is next in the list doesn't get skipped.

Comment (corp-0) [reply UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs]: yeah, I understood that. Still, I think it is clearer to iterate backwards so the index doesn't change when you delete an element.

File: UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs (hunk 1 above)
Comment (CorruptComputer) [reply UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs]: Moved these to their own methods, both here and in the servers panel

File: UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs (hunk 2 above)
Comment (CorruptComputer) [reply UnitystationLauncher/ViewModels/InstallationsPanelViewModel.cs]: Made it so the remove operation iterates backwards both here and in the servers panel

**Review by corp-0 — APPROVED** [review]
