### PR TITLE
Corrects path to game executable file in MacOSX

### LINKED ISSUE #114: extracting zip files doesn't preserve file permissions.
OS: MacOS Catalina 10.15
version: 928 and latest from repo.

EDIT: 

The real problem with MacOS being unable to launch the game from hub was that the way we unzip the .app bundle doesn't preserve file permissions. 

A solution would be making hub set the file permissions for the executable after extracting.

This problem should also affect Linux.

_________________________________________________________________________________________________________________________
So executing the application wasn't the only problem we face, launching the game from the application is also erroring.

Steps:
1- Run the application using ``./StationHub``
2- Downlaod a game build and try to launch it

error from log:
```
[16:53:47 INF] Start OSX
LSOpenURLsWithRole() failed for the application /Users/pichula/.local/share/StationHub/Installations/Unitystation4121/Unitystation.app with error -10810
```

### PR DESCRIPTION
**Pull request by corp-0**
Bug was pretty easy to fix but a hurdly to understand, fukken MacOSX and their *different* OS. 

This will let StationHub launch the game again on MacOSX.
fixes #114

### CODE REVIEW

File: UnitystationLauncher/Models/Installation.cs [hunk 1]
```diff
@@ -46,8 +46,7 @@ public Installation(string folderPath)
             }
             else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
             {
-                var archives = Directory.EnumerateDirectories(path);
-                exe = archives.SingleOrDefault(s => Regex.IsMatch(Path.GetFileName(s), @".*station\.app"));
+                exe = Path.Combine(path, "Unitystation.app", "Contents", "MacOS", "unitystation");
```
Comment (RedlineTriad) [inline UnitystationLauncher/Models/Installation.cs:48]: I made it search for the exe so forks can use a different name from `Unitystation`.
I would either implement the search functionality so it works, fix the file name, or make all of the other platform specific implementations match this one.

**Review by RedlineTriad — CHANGES_REQUESTED** [review]

File: UnitystationLauncher/Models/Installation.cs (hunk 1 above)
Comment (corp-0) [reply UnitystationLauncher/Models/Installation.cs:48]: done

**Review by RedlineTriad — APPROVED** [review]
